=pod

=head1 NAME

podcastr - A Python podcast updater

=head1 SYNOPSIS 
  
  podcastr does not use in aguments in this release.

=head1 NOTICES

* Podcastr does not include a configuration file or support multiple file
downloads within a podcast in this release.

* The file podcastr must be edited with the appropriate information in this
release.

=head1 REQUIREMENTS 
	python 2.5.*
	urllib module for python (Arch User Repository: python-urljr)
	feedparser module for python (AUR: python-feedparser)
  eyeD3 module for python (AUR: python-eyed3)

